site_name: FIND Documentation
theme: cosmo
repo_url: https://github.com/schollz/find
site_description: API documentation for schollz/find, a Framework for Internal Positioning and WiFi based location
site_url: https://docs.internalpositioning.com
site_author: Zack
pages:
  - 'Quickstart': index.md
  - 'Setup': setup.md
  - 'API': api.md
  - 'FAQ': faq.md
  - 'Home Automation': ha.md
  - 'Privacy Policy': privacy.md

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
